# Generated by Django 4.2.1 on 2023-05-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DayName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            (1, "Poniedziałek"),
                            (2, "Wtorek"),
                            (3, "Środa"),
                            (4, "Czwartek"),
                            (5, "Piątek"),
                            (6, "Sobota"),
                            (7, "Niedziela"),
                        ],
                        default=1,
                        max_length=32,
                    ),
                ),
            ],
        ),
    ]
