# Generated by Django 4.2.1 on 2023-05-10 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trainerapp", "0002_exercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainerapp.dayname",
                    ),
                ),
                (
                    "exercise_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainerapp.exercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=255)),
                (
                    "exercises",
                    models.ManyToManyField(
                        through="trainerapp.ExerciseTraining", to="trainerapp.exercise"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=255)),
                (
                    "trainings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainerapp.training",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exercisetraining",
            name="training_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trainerapp.training"
            ),
        ),
    ]
