# Generated by Django 4.2.1 on 2023-05-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainerapp", "0002_alter_exercise_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingplan",
            name="trainings",
            field=models.ManyToManyField(to="trainerapp.training"),
        ),
    ]
