# Generated by Django 4.2.1 on 2023-05-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainerapp", "0005_alter_training_exercises_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingplan",
            name="trainings",
        ),
        migrations.AddField(
            model_name="trainingplan",
            name="trainings",
            field=models.ManyToManyField(null=True, to="trainerapp.training"),
        ),
    ]
