# Generated by Django 4.2.1 on 2023-05-22 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trainerapp", "0006_remove_trainingplan_trainings_trainingplan_trainings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="training",
            name="day_name",
        ),
    ]
