version: "3"
services:
  trainerconnectapp:
    container_name: TrainerConnect
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    network_mode: "host"