# Generated by Django 4.2.1 on 2023-05-31 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="thread",
        ),
        migrations.AddField(
            model_name="thread",
            name="messages",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.message",
            ),
        ),
    ]
